export enum USER_ROLES {
  ACCOUNT_OWNER = 'Account Owner',
  ADMIN = 'Admin',
  DOCTOR = 'Doctor',
  STAFF = 'Staff',
  PATIENT = 'Patient',
  SYSTEM_ADMIN = 'System Admin',
}

export enum DB_ACTIONS {
  INSERT = 'INSERT',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  VIEW = 'VIEW',
}

export enum RESOURCES {
  MANAGE_PRACTICE_ACCOUNT = 'MANAGE_PRACTICE_ACCOUNT',
  MANAGE_USER = 'MANAGE_USER',
  MANAGE_PATIENT = 'MANAGE_PATIENT',
}

type TRoleAccess = {
  [T in USER_ROLES]: {
    [U in RESOURCES]?: DB_ACTIONS[];
  };
};

export const ROLE_ACCESS: TRoleAccess = {
  [USER_ROLES.ACCOUNT_OWNER]: {
    [RESOURCES.MANAGE_PRACTICE_ACCOUNT]: [DB_ACTIONS.INSERT, DB_ACTIONS.UPDATE, DB_ACTIONS.DELETE, DB_ACTIONS.VIEW],
    [RESOURCES.MANAGE_USER]: [DB_ACTIONS.INSERT, DB_ACTIONS.UPDATE, DB_ACTIONS.DELETE, DB_ACTIONS.VIEW],
    [RESOURCES.MANAGE_PATIENT]: [DB_ACTIONS.INSERT, DB_ACTIONS.UPDATE, DB_ACTIONS.DELETE, DB_ACTIONS.VIEW],
  },
  [USER_ROLES.ADMIN]: {
    [RESOURCES.MANAGE_PRACTICE_ACCOUNT]: [DB_ACTIONS.VIEW],
    [RESOURCES.MANAGE_USER]: [DB_ACTIONS.INSERT, DB_ACTIONS.UPDATE, DB_ACTIONS.DELETE, DB_ACTIONS.VIEW],
    [RESOURCES.MANAGE_PATIENT]: [DB_ACTIONS.INSERT, DB_ACTIONS.UPDATE, DB_ACTIONS.DELETE, DB_ACTIONS.VIEW],
  },
  [USER_ROLES.DOCTOR]: {
    [RESOURCES.MANAGE_PRACTICE_ACCOUNT]: [DB_ACTIONS.VIEW],
    [RESOURCES.MANAGE_USER]: [DB_ACTIONS.INSERT, DB_ACTIONS.UPDATE, DB_ACTIONS.DELETE, DB_ACTIONS.VIEW],
    [RESOURCES.MANAGE_PATIENT]: [DB_ACTIONS.INSERT, DB_ACTIONS.UPDATE, DB_ACTIONS.DELETE, DB_ACTIONS.VIEW],
  },
  [USER_ROLES.STAFF]: {
    [RESOURCES.MANAGE_PRACTICE_ACCOUNT]: [DB_ACTIONS.VIEW],
    [RESOURCES.MANAGE_USER]: [DB_ACTIONS.VIEW],
  },
  [USER_ROLES.PATIENT]: {
    [RESOURCES.MANAGE_PRACTICE_ACCOUNT]: [], // no access
    [RESOURCES.MANAGE_USER]: [], // no access
  },
  [USER_ROLES.SYSTEM_ADMIN]: {
    [RESOURCES.MANAGE_PRACTICE_ACCOUNT]: [DB_ACTIONS.VIEW], // no access
    [RESOURCES.MANAGE_USER]: [DB_ACTIONS.VIEW], // no access
  },
};
